DVO-4739 parameter ignore-failures

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -45,6 +45,10 @@ inputs:
     description: 'set to true if you wish to fail this run when the Quality Gate is red'
     required: false
     default: true
+  ignore-failures:
+    description: 'Ignore Sonar Quality Gate. Set sonar'
+    required: false
+    default: ''
     
 runs:
   using: 'composite'
@@ -87,14 +91,14 @@ runs:
       shell: bash
         
     - name: Containerized Dependencies   
-      if: ${{ inputs.use-dependencies == 'true' && inputs.path-to-repo-root == '' }}    
+      if: ${{ (inputs.use-dependencies == 'true') && (inputs.path-to-repo-root == '') }}    
       run: |
         echo "Containerized Dependencies Running docker compose"
         docker-compose -f ${{ inputs.docker-compose-file-path }} up -d
       shell: bash
 
     - name: Containerized Dependencies with Path   
-      if: ${{ inputs.use-dependencies == 'true' && inputs.path-to-repo-root != '' }}    
+      if: ${{ (inputs.use-dependencies == 'true') && (inputs.path-to-repo-root != '') }}    
       run: |
         echo "Containerized Dependencies Running docker compose with path"
         PATH_TO_REPO_ROOT='${{ inputs.path-to-repo-root }}' docker-compose -f ${{ inputs.docker-compose-file-path }} up -d
@@ -147,7 +151,7 @@ runs:
 
     - name: SonarQube Quality Gate check
       uses: sonarsource/sonarqube-quality-gate-action@master
-      if: ${{ inputs.fail-on-failure == 'true' }}
+      if: ${{ (inputs.fail-on-failure == 'true') || (inputs.ignore-failures != 'sonar') }}
       env:
         SONAR_TOKEN: ${{ inputs.sonar-token }}
       with:
@@ -166,7 +170,7 @@ runs:
         reporter: dotnet-trx
 
     - name: Stop Containerized Dependencies
-      if: ${{ inputs.use-dependencies == 'true' && always() }}
+      if: ${{ (inputs.use-dependencies == 'true') && always() }}
       run: |
         echo "Containerized Dependencies: Stopping Docker Containers"
         docker-compose -f ${{inputs.docker-compose-file-path}} down -v --remove-orphans
